In [1]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [4]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1

In [2]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)
print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7

In [8]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

In [9]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [27]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print('\n',df) 
#refer to the row index:
print('\n',df.loc[0])
#use a list of indexes:
print('\n',df.loc[[0, 1]])

    calories  duration
0       420        50
1       380        40
2       390        45

 calories    420
duration     50
Name: 0, dtype: int64

    calories  duration
0       420        50
1       380        40

In [28]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print('\n',df)
#refer to the named index:
print('\n',df.loc["day2"])

       calories  duration
day1       420        50
day2       380        40
day3       390        45

 calories    380
duration     40
Name: day2, dtype: int64

In [40]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [41]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [42]:
import pandas as pd

print(pd.options.display.max_rows)

60

In [43]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))

   Duration  Pulse  Maxpulse  Calories        Date
0        60    110       130     409.1  07/01/2015
1        60    117       145     479.0  01/01/2015
2        60    103       135     340.0  02/01/2015
3        45    109       175     282.4  03/01/2015
4        45    117       148     406.0  04/01/2015
5        60    102       127     300.0  05/01/2015
6        60    100       120     250.0  25/01/2015
7        45    104       134     253.3  07/01/2015
8        30    109       133     195.1  08/01/2015
9        60     98       124     269.0  09/01/2015

In [44]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.tail())

    Duration  Pulse  Maxpulse  Calories        Date
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [45]:
import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna()

print(new_df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [46]:
import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [47]:
import pandas as pd

df = pd.read_csv('data.csv')

df.fillna(130, inplace = True) 
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     130.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     130.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [48]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mean()

df["Calories"].fillna(x, inplace = True) 

print(df.to_string())

    Duration  Pulse  Maxpulse    Calories        Date
0         60    110       130  409.100000  07/01/2015
1         60    117       145  479.000000  01/01/2015
2         60    103       135  340.000000  02/01/2015
3         45    109       175  282.400000  03/01/2015
4         45    117       148  406.000000  04/01/2015
5         60    102       127  300.000000  05/01/2015
6         60    100       120  250.000000  25/01/2015
7         45    104       134  253.300000  07/01/2015
8         30    109       133  195.100000  08/01/2015
9         60     98       124  269.000000  09/01/2015
10        60    103       147  329.300000  10/01/2015
11        60    100       120  250.700000  07/01/2015
12        60    106       128  345.300000  12/01/2015
13        60    104       132  379.300000  13/01/2015
14        60    100       120  250.000000  25/01/2015
15        60     98       120  215.200000  15/01/2015
16        60    100       120  300.000000  15/01/2015
17        45     90       112  301.093617  17/01/2015
18        60    103       123  323.000000  18/01/2015
19        45     97       125  243.000000  19/01/2015
20        60    108       131  364.200000  20/01/2015
21        45    100       119  282.000000  21/01/2015
22        60    130       101  300.000000  22/01/2015
23        45    105       132  246.000000  23/01/2015
24        60    100       120  250.000000  25/01/2015
25        60    100       120  250.000000  25/01/2015
26        60     92       118  241.000000  21/01/2015
27        60    103       132  301.093617  27/01/2015
28        60    100       132  280.000000  28/01/2015
29        60    102       129  380.300000  29/01/2015
30        60     92       115  243.000000  30/01/2015
31        45     90       112  180.100000  31/01/2015
32        60    101       124  299.000000  01/02/2015
33        60     93       113  223.000000  02/02/2015
34        60    107       136  361.000000  03/02/2015
35        60    114       140  415.000000  04/02/2015
36        60    102       127  300.000000  05/02/2015
37        60    100       120  300.000000  06/02/2015
38        60    100       120  300.000000  07/02/2015
39        45    104       129  266.000000  08/02/2015
40        45     90       112  180.100000  09/02/2015
41        60     98       126  286.000000  10/02/2015
42        60    100       122  329.400000  11/02/2015
43        60    111       138  400.000000  12/02/2015
44        60    111       131  397.000000  13/02/2015
45        60     99       119  273.000000  08/02/2015
46        60    109       153  387.600000  15/02/2015
47        45    111       136  300.000000  16/02/2015
48        45    108       129  298.000000  17/02/2015

In [49]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].median()

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     299.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     299.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [50]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     300.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     300.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [51]:
import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(subset=['Date'], inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [65]:
import pandas as pd

df = pd.read_csv('data.csv')

df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories       Date
0         60    110       130     409.1 2015-01-07
1         60    117       145     479.0 2015-01-01
2         60    103       135     340.0 2015-01-02
3         45    109       175     282.4 2015-01-03
4         45    117       148     406.0 2015-01-04
5         60    102       127     300.0 2015-01-05
6         60    100       120     250.0 2015-01-25
7         45    104       134     253.3 2015-01-07
8         30    109       133     195.1 2015-01-08
9         60     98       124     269.0 2015-01-09
10        60    103       147     329.3 2015-01-10
11        60    100       120     250.7 2015-01-07
12        60    106       128     345.3 2015-01-12
13        60    104       132     379.3 2015-01-13
14        60    100       120     250.0 2015-01-25
15        60     98       120     215.2 2015-01-15
16        60    100       120     300.0 2015-01-15
17        45     90       112       NaN 2015-01-17
18        60    103       123     323.0 2015-01-18
19        45     97       125     243.0 2015-01-19
20        60    108       131     364.2 2015-01-20
21        45    100       119     282.0 2015-01-21
22        60    130       101     300.0 2015-01-22
23        45    105       132     246.0 2015-01-23
24        60    100       120     250.0 2015-01-25
25        60    100       120     250.0 2015-01-25
26        60     92       118     241.0 2015-01-21
27        60    103       132       NaN 2015-01-27
28        60    100       132     280.0 2015-01-28
29        60    102       129     380.3 2015-01-29
30        60     92       115     243.0 2015-01-30
31        45     90       112     180.1 2015-01-31
32        60    101       124     299.0 2015-02-01
33        60     93       113     223.0 2015-02-02
34        60    107       136     361.0 2015-02-03
35        60    114       140     415.0 2015-02-04
36        60    102       127     300.0 2015-02-05
37        60    100       120     300.0 2015-02-06
38        60    100       120     300.0 2015-02-07
39        45    104       129     266.0 2015-02-08
40        45     90       112     180.1 2015-02-09
41        60     98       126     286.0 2015-02-10
42        60    100       122     329.4 2015-02-11
43        60    111       138     400.0 2015-02-12
44        60    111       131     397.0 2015-02-13
45        60     99       119     273.0 2015-02-08
46        60    109       153     387.6 2015-02-15
47        45    111       136     300.0 2015-02-16
48        45    108       129     298.0 2015-02-17

In [55]:
import pandas as pd

df = pd.read_csv('data.csv')

df.loc[7,'Duration'] = 45

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [57]:
import pandas as pd

df = pd.read_csv('data.csv')

for x in df.index:
      if df.loc[x, "Duration"] > 120:
        df.loc[x, "Duration"] = 120

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [58]:
import pandas as pd

df = pd.read_csv('data.csv')

for x in df.index:
      if df.loc[x, "Duration"] > 120:
        df.drop(x, inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60    100       120     250.0  25/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    100       120     250.0  25/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [59]:
import pandas as pd

df = pd.read_csv('data.csv')

df.drop_duplicates(inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  07/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    100       120     250.0  25/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112       NaN  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132       NaN  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [60]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25     True
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
dtype: bool

In [64]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.corr(numeric_only=True))

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.000786 -0.142530  0.382701
Pulse    -0.000786  1.000000  0.451368  0.645960
Maxpulse -0.142530  0.451368  1.000000  0.515910
Calories  0.382701  0.645960  0.515910  1.000000